Repository NREL/openstudio-standards, pull requests merged in 2022-01, with the labels that each got.

#1249 Fix ERV lookup for 90.1-2019, avoid multiple lookup results to be ret…
  lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.AirLoopHVAC.rb
Labels: 90.1-2016/9

#1246 Style formatting - adding two parameters with default values
  lib/openstudio-standards/standards/Standards.Model.rb
  lib/openstudio-standards/standards/Standards.PlantLoop.rb
  lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.PlantLoop.rb
Labels: AppendixG

#1230 CHW and HW supply temperature setpoint reset
  lib/openstudio-standards/standards/Standards.Model.rb
  lib/openstudio-standards/standards/ashrae_90_1_prm/docs/set_hw_and_chw_supply_water_temp_reset_control.md
  openstudio-standards.gemspec
  test/90_1_prm/data/prototype_list.json
  test/90_1_prm/test_appendix_g_prm.rb
Labels: AppendixG

#1255 Implement new workflow to search constructions.
  lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb
  lib/openstudio-standards/standards/Standards.Model.rb
  lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/ashrae_90_1_2004.Model.rb
  test/doe_prototype/test_small_office.rb
Labels: Standard - 90.1
